service: my-shop-app

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1

plugins:
  - serverless-finch
  - serverless-single-page-app-plugin

custom:
  client:
    bucketName: cloudx-course
    distributionFolder: dist/app/browser
    indexDocument: index.html
    errorDocument: index.html

functions: {}
